// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJBy06d_l1yYQRz7QZM6bnfyzk_QqHp20',
    appId: '1:1053571733034:web:914876f1ae5c521ab35553',
    messagingSenderId: '1053571733034',
    projectId: 'ecotrack-davi',
    authDomain: 'ecotrack-davi.firebaseapp.com',
    storageBucket: 'ecotrack-davi.firebasestorage.app',
    measurementId: 'G-FJSNCWN6DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6xRGueepK7PgkCUzKChg8FORLA9Cghk8',
    appId: '1:1053571733034:android:fe2c50c57ce83cbeb35553',
    messagingSenderId: '1053571733034',
    projectId: 'ecotrack-davi',
    storageBucket: 'ecotrack-davi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYlTTFg6jiXVU2QK5xy8DczunZ_vt0RDI',
    appId: '1:1053571733034:ios:53c12c0f2faca5c7b35553',
    messagingSenderId: '1053571733034',
    projectId: 'ecotrack-davi',
    storageBucket: 'ecotrack-davi.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYlTTFg6jiXVU2QK5xy8DczunZ_vt0RDI',
    appId: '1:1053571733034:ios:53c12c0f2faca5c7b35553',
    messagingSenderId: '1053571733034',
    projectId: 'ecotrack-davi',
    storageBucket: 'ecotrack-davi.firebasestorage.app',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJBy06d_l1yYQRz7QZM6bnfyzk_QqHp20',
    appId: '1:1053571733034:web:5ff780610c74b1a3b35553',
    messagingSenderId: '1053571733034',
    projectId: 'ecotrack-davi',
    authDomain: 'ecotrack-davi.firebaseapp.com',
    storageBucket: 'ecotrack-davi.firebasestorage.app',
    measurementId: 'G-WXVGM6992C',
  );
}
